name: geoflutterfire2
description: GeoFlutterFire for Flutter, compatible with cloud_firestore ^6.0.0
version: 2.3.16
homepage: https://github.com/yourusername/geoflutterfire2

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.0.0
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
